
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-app-mydomain-v1-sampleapp
  failurePolicy: Fail
  name: msampleapp.kb.io
  rules:
  - apiGroups:
    - app.mydomain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sampleapps

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-app-mydomain-v1-sampleapp
  failurePolicy: Fail
  name: vsampleapp.kb.io
  rules:
  - apiGroups:
    - app.mydomain
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sampleapps
