# permissions to do viewer sampleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sampleapp-viewer-role
rules:
- apiGroups:
  - app.mydomain
  resources:
  - sampleapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.mydomain
  resources:
  - sampleapps/status
  verbs:
  - get
